export enum apiRoutesEnum {
  users = "/api/users",
  company = "/api/company",
  me = "/api/users/me",
  logout = "/api/auth/log-out",
  sign_in = "/api/auth/sign-in",
  sign_up = "/api/auth/sign-up",
  legal_entity = "/api/legal-entity",
  address = "/api/address",
  currency = "/api/currency",
  permission = "/api/permission",
  entity = "/api/entity",
  role = "/api/role",
  account = "/api/account",
  beneficiary = "/api/beneficiary",
  rates = "/api/rates",
  bank_holder = "/api/bank-holder",
  balance_history = "/api/balance-history",
  category = "/api/category",
  transactions = "/api/transactions",
  rules = "/api/rules",
  project = "/api/project",
  planned_budget = "/api/planed-budget",
}
